name: ESANN-2024
channels:
  - conda-forge
  - rapidsai
  - nvidia
  - pytorch
dependencies:
  - python=3.11.9
  - pandas=2.2.2
  - pyarrow=15.0.2
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - scikit-learn=1.3.0
  - numpy=1.26.4
  - transformers=4.39.3
  - pip:
      - pytreebank==0.2.7