name: QNLP-2024
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11.9
  - pandas=2.2.2
  - pyarrow=15.0.2
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - scikit-learn=1.4.2
  - numpy=1.26.4
  - transformers=4.39.3
  - pennylane=0.35.1
  - py-xgboost-gpu=2.0.3
  - matplotlib=3.8.4
  - nltk=3.8.1
  - pip:
      - pytreebank==0.2.7
